import { supabase } from '../lib/supabase'
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
export function generateArticleContent(title, products) {
  const rows = products.map(p => `<tr><td>${p.name}</td><td>₹${p.price}</td><td>★ ${p.rating || '—'}</td><td>${p.review_verdict || p.review_summary || 'Everyday use'}</td></tr>`).join('')
  const sections = products.map((p, i) => `<hr><h2>${i + 1}. ${p.name}</h2><p><strong>Price:</strong> ₹${p.price} &nbsp; <strong>Rating:</strong> ★ ${p.rating || '—'}</p><h3>Why we like it</h3><p>${p.review_summary || p.review || 'A practical PickWise recommendation.'}</p>${p.review_pros?.length ? `<h3>Pros</h3><ul>${p.review_pros.map(x => `<li>${x}</li>`).join('')}</ul>` : ''}${p.review_cons?.length ? `<h3>Cons</h3><ul>${p.review_cons.map(x => `<li>${x}</li>`).join('')}</ul>` : ''}<p><a href="${p.affiliate_link}" target="_blank" rel="nofollow noopener">Check price on ${p.shop} →</a></p>`).join('')
  return `<h1>${title}</h1><p>Looking for well-reviewed products? These are our favourite picks, selected from products tested and reviewed by PickWise.</p><h2>Quick comparison</h2><table><thead><tr><th>Product</th><th>Price</th><th>Rating</th><th>Best for</th></tr></thead><tbody>${rows}</tbody></table>${sections}`
}
export async function getAll(studio = false) { let q = supabase.from('articles').select('*, categories(name, emoji), article_products(product_id, products(id,name,image_url,price,rating,shop))').order('created_at',{ascending:false}); if (!studio) q=q.eq('status','published'); const {data,error}=await q; if(error) throw error; return data }
export async function getBySlug(slug) { const {data,error}=await supabase.from('articles').select('*, categories(name, emoji), article_products(display_order, products(*, categories(name,emoji,color)) )').eq('slug',slug).eq('status','published').single(); if(error) throw error; return data }
export async function create(article, productIds) { const {data,error}=await supabase.from('articles').insert([{...article, slug: slugify(article.slug || article.title), published_at: article.status==='published' ? new Date().toISOString() : null}]).select().single(); if(error) throw error; if(productIds.length) { const {error:e}=await supabase.from('article_products').insert(productIds.map((product_id,display_order)=>({article_id:data.id,product_id,display_order}))); if(e) throw e } return data }
