import { useEffect, useState } from 'react'
import StudioLayout from '../../components/studio/StudioLayout'
import * as productsService from '../../services/productsService'
import * as articlesService from '../../services/articlesService'
export default function Articles() {
  const [products,setProducts]=useState([]),[articles,setArticles]=useState([]),[title,setTitle]=useState(''),[selected,setSelected]=useState([]),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const load=()=>articlesService.getAll(true).then(setArticles).catch(err=>setError(`Could not load articles: ${err.message}`))
  useEffect(()=>{productsService.getAll({published:'published'}).then(r=>setProducts(r.data)).catch(err=>setError(`Could not load products: ${err.message}`));load()},[])
  const save=async status=>{setMessage('');setError('');const picks=products.filter(p=>selected.includes(p.id));if(!title.trim()){setError('Enter a guide title first.');return}if(!picks.length){setError('Select at least one product to generate a guide.');return}setSaving(true);try{await articlesService.create({title:title.trim(),status,excerpt:`Our favourite picks from ${title}.`,content:articlesService.generateArticleContent(title,picks)},selected);setMessage(status==='published'?'Guide published successfully.':'Draft generated successfully.');setTitle('');setSelected([]);load()}catch(err){setError(`Could not create the guide. Run the 009_articles.sql migration in Supabase, then try again. (${err.message})`)}finally{setSaving(false)}}
  return <StudioLayout title="Articles"><div style={{maxWidth:760}}><h2>New Buying Guide</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Best Kitchen Gadgets Under ₹500" style={{width:'100%',padding:12}}/><p>Select products ({selected.length} selected)</p>{products.map(p=><label key={p.id} style={{display:'block',padding:'5px 0',cursor:'pointer'}}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}/> {p.name} — ₹{p.price}</label>)}<div style={{display:'flex',gap:10,margin:'18px 0',position:'sticky',bottom:0,background:'#fff',padding:'12px 0'}}><button disabled={saving} onClick={()=>save('draft')}>{saving?'Generating…':'Generate Draft'}</button><button disabled={saving} onClick={()=>save('published')}>{saving?'Generating…':'Generate & Publish'}</button></div>{error&&<p role="alert" style={{color:'#b91c1c',fontWeight:600}}>{error}</p>}{message&&<p role="status" style={{color:'#047857',fontWeight:600}}>{message}</p>}<h2>Articles</h2>{articles.map(a=><p key={a.id}>{a.title} — {a.status}</p>)}</div></StudioLayout>
}
